### ISSUE TITLE
Add a section describing how to setup ENS environment locally

### ISSUE THREAD

**Issue by makoto** [ensdomains/docs#1]
We need a section describing how to setup ENS locally (eg: to ganache) and register some sample names.

Ideally using the followings

- https://truffleframework.com
- https://embark.status.im
- https://getwaffle.io
- web3.py/web3.j (no idea how it works though).

**Comment by makoto** [comment]
https://github.com/EthWorks/ENSBuilder allows you to deploy ENS locally as well

**Comment by Arachnid** [comment]
Done: https://ens.gitbook.io/ens/deploying-ens-on-a-private-chain

**Comment by makoto** [comment]
Please also mention how to specify the register the locally deployed address to the ENS library

**Comment by makoto** [comment]
V2 requires ensAddress at instantiation https://github.com/ensdomains/ensjs
