### ISSUE TITLE
difference between 'name' and 'domain'

### ISSUE THREAD

**Issue by kangarang** [ensdomains/docs#14]
hello, i'd like to know the primary difference between a `name` and a `domain`. is it that a `name` is specified as consisting of at least two `label`s... whereas `domain` is more of a generic, colloquial term available for derivation (`domain`, `TLD`, `subdomain`)?

e.g.
valid `name`s:
- `alice.eth`
- `iam.alice.eth`

valid "domain"s:
- `eth`
- `.eth`
- `alice.eth`
- `iam.alice.eth`

**Comment by Arachnid** [comment]
Colloquially, the two are used interchangeably. I don't think you can draw a hard distinction between the two based on usage.

**Comment by kangarang** [comment]
ah i see, thank you for clarifying!
