### ISSUE TITLE
Outdated links

### ISSUE THREAD

**Issue by jannikluhn** [ensdomains/docs#145]
The links on the following lines don't work anymore:

https://github.com/ensdomains/docs/blob/7d0e70ff1640fa5b052d04c63f5ec19f7144fddd/ens-deployments.md#L15
https://github.com/ensdomains/docs/blob/7d0e70ff1640fa5b052d04c63f5ec19f7144fddd/ens-deployments.md#L23

**Comment by lucemans** [comment]
Issue appears to still be relevant.

Will update the links but might be good to have the correct redirect URLs in place.

Re ENS Manager App
CC @LeonmanRolls @TateB
