### ISSUE TITLE
deployments on private chains

### ISSUE THREAD

**Issue by ericobi** [ensdomains/docs#156]
https://docs.ens.domains/deploying-ens-on-a-private-chain

Can we update this page? It is not using the latest version of ens-contracts and showing errors.

**Comment by lilyanB** [comment]
do you know how to do the deployment? Because the tuto doesn't work and I'd like to do it now.

**Comment by kaliubuntu0206** [comment]
@Arachnid Could you update the docs? I need ENS on my Hardhat node to test ENS intergrations

**Comment by kaliubuntu0206** [comment]
I could not guarantee if it works but here is my contract to make the ENS deploy attempt.

```
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.4;

import {INameWrapper, PublicResolver} from '@ensdomains/ens-contracts/contracts/resolvers/PublicResolver.sol';
import '@ensdomains/ens-contracts/contracts/registry/ENSRegistry.sol';
import '@ensdomains/ens-contracts/contracts/registry/FIFSRegistrar.sol';
import {NameResolver, ReverseRegistrar} from '@ensdomains/ens-contracts/contracts/reverseRegistrar/ReverseRegistrar.sol';

/// @dev https://docs.ens.domains/deploying-ens-on-a-private-chain#deploying-ens-in-a-single-transaction
/// @dev Modified to make it compatible with recent updates however not audited
contract ENSDeployer {
    bytes32 public constant TLD_LABEL = keccak256('eth');
    bytes32 public constant RESOLVER_LABEL = keccak256('resolver');
    bytes32 public constant REVERSE_REGISTRAR_LABEL = keccak256('reverse');
    bytes32 public constant ADDR_LABEL = keccak256('addr');

    ENSRegistry public ens;
    FIFSRegistrar public fifsRegistrar;
    ReverseRegistrar public reverseRegistrar;
    PublicResolver public publicResolver;

    function namehash(bytes32 node, bytes32 label) public pure returns (bytes32) {
        return keccak256(abi.encodePacked(node, label));
    }

    constructor() {
        ens = new ENSRegistry();
        publicResolver = new PublicResolver(ens, INameWrapper(address(0)), address(0), address(0));

        // Set up the resolver
        bytes32 resolverNode = namehash(bytes32(0), RESOLVER_LABEL);

        ens.setSubnodeOwner(bytes32(0), RESOLVER_LABEL, address(this));
        ens.setResolver(resolverNode, address(publicResolver));
        publicResolver.setAddr(resolverNode, address(publicResolver));

        // Create a FIFS registrar for the TLD
        fifsRegistrar = new FIFSRegistrar(ens, namehash(bytes32(0), TLD_LABEL));

        ens.setSubnodeOwner(bytes32(0), TLD_LABEL, address(fifsRegistrar));

        // Construct a new reverse registrar and point it at the public resolver
        reverseRegistrar = new ReverseRegistrar(ens);

        // Set up the reverse registrar
        ens.setSubnodeOwner(bytes32(0), REVERSE_REGISTRAR_LABEL, address(this));
        ens.setSubnodeOwner(
            namehash(bytes32(0), REVERSE_REGISTRAR_LABEL),
            ADDR_LABEL,
            address(reverseRegistrar)
        );

        // Set default resolver to PublicResolver
        reverseRegistrar.setDefaultResolver(address(publicResolver));
    }
}
```

**Comment by lilyanB** [comment]
> I could not guarantee if it works but here is my contract to make the ENS deploy attempt.
> 
> ```
> // SPDX-License-Identifier: MIT
> pragma solidity >=0.8.4;
> 
> import {INameWrapper, PublicResolver} from '@ensdomains/ens-contracts/contracts/resolvers/PublicResolver.sol';
> import '@ensdomains/ens-contracts/contracts/registry/ENSRegistry.sol';
> import '@ensdomains/ens-contracts/contracts/registry/FIFSRegistrar.sol';
> import {NameResolver, ReverseRegistrar} from '@ensdomains/ens-contracts/contracts/reverseRegistrar/ReverseRegistrar.sol';
> 
> /// @dev https://docs.ens.domains/deploying-ens-on-a-private-chain#deploying-ens-in-a-single-transaction
> /// @dev Modified to make it compatible with recent updates however not audited
> contract ENSDeployer {
>     bytes32 public constant TLD_LABEL = keccak256('eth');
>     bytes32 public constant RESOLVER_LABEL = keccak256('resolver');
>     bytes32 public constant REVERSE_REGISTRAR_LABEL = keccak256('reverse');
>     bytes32 public constant ADDR_LABEL = keccak256('addr');
> 
>     ENSRegistry public ens;
>     FIFSRegistrar public fifsRegistrar;
>     ReverseRegistrar public reverseRegistrar;
>     PublicResolver public publicResolver;
> 
>     function namehash(bytes32 node, bytes32 label) public pure returns (bytes32) {
>         return keccak256(abi.encodePacked(node, label));
>     }
> 
>     constructor() {
>         ens = new ENSRegistry();
> 
>         // Create a FIFS registrar for the TLD
>         fifsRegistrar = new FIFSRegistrar(ens, namehash(bytes32(0), TLD_LABEL));
> 
>         ens.setSubnodeOwner(bytes32(0), TLD_LABEL, address(fifsRegistrar));
> 
>         // Construct a new reverse registrar and point it at the public resolver
>         reverseRegistrar = new ReverseRegistrar(ens);
> 
>         // Set up the reverse registrar
>         ens.setSubnodeOwner(bytes32(0), REVERSE_REGISTRAR_LABEL, address(this));
>         ens.setSubnodeOwner(
>             namehash(bytes32(0), REVERSE_REGISTRAR_LABEL),
>             ADDR_LABEL,
>             address(reverseRegistrar)
>         );
> 
>         publicResolver = new PublicResolver(ens, INameWrapper(address(0)), address(0), address(reverseRegistrar));
> 
>         // Set up the resolver
>         bytes32 resolverNode = namehash(bytes32(0), RESOLVER_LABEL);
> 
>         ens.setSubnodeOwner(bytes32(0), RESOLVER_LABEL, address(this));
>         ens.setResolver(resolverNode, address(publicResolver));
>         publicResolver.setAddr(resolverNode, address(publicResolver));
> 
>         // Set default resolver to PublicResolver
>         reverseRegistrar.setDefaultResolver(address(publicResolver));
> 
>         // Set owner to deployer
>         ens.setOwner(bytes32(0), msg.sender);
>     }
> }
> ```
> 
> @Arachnid If you don't update the docs to work with latest contract, maybe people would attempt to deploy ENS with my incomplete deploy contract.

Thanks, do you know how to interact with custom ENS? Because wagmi or ensjs (in doc) works with contract information already deployed. example: "useEnsAddress" with wagmi. How do we modify the chain and the address used to match our custom ENS on our private chain?

**Comment by kaliubuntu0206** [comment]
@ericobi Haven't tried with wagmi but with ethers.js adding custom registry address will work

**Comment by lilyanB** [comment]
> @ericobi Haven't tried with wagmi but with ethers.js adding custom registry address will work

can you please share your code with etherjs? Because when I deploy the ens contracts I can't interact with them.

**Comment by lucemans** [comment]
Will make a more updated guide on how to deploy ENS locally post v2 of the docs framework.
The current document is a bit out of date 🙈
