### ISSUE TITLE
ENSIP12 messy formatting 

### ISSUE THREAD

**Issue by jefflau** [ensdomains/docs#235]
<img width="874" alt="Screenshot 2024-05-02 at 13 30 11" src="https://github.com/ensdomains/docs/assets/1221141/2708261e-7600-42b0-930f-fc31302fdc6c">

**Comment by sofiiiiiiaaaa** [comment]
> <img alt="Screenshot 2024-05-02 at 13 30 11" width="874" src="https://private-user-images.githubusercontent.com/1221141/327319900-2708261e-7600-42b0-930f-fc31302fdc6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NjAxMTUsIm5iZiI6MTcxNDc1OTgxNSwicGF0aCI6Ii8xMjIxMTQxLzMyNzMxOTkwMC0yNzA4MjYxZS03NjAwLTQyYjAtOTMwZi1mYzMxMzAyZmRjNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMTgxMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDNmYjhjNTkxYWY3MzI3ZjZlODk1NWU4ZDNlNDllY2QzMjZhYjcxY2Y0Njk3Yzc2ZmM0YWZmZGVhY2NmZjcwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oz65rcSqOkEjgbUx8aj9vSk770D8VRtQinZVUguNWDA">
