### ISSUE TITLE
Add docs on how to set up Tor .onion resolution

### ISSUE THREAD

**Issue by TheodoreChu** [ensdomains/docs#47]
ENS domains can be set up to resolve to .onion names as discussed in the following blog posts:

- https://medium.com/the-ethereum-name-service/list-of-ens-names-that-resolve-to-tor-onion-websites-99140a4c674f
- https://medium.com/the-ethereum-name-service/ens-now-supports-tor-onion-address-resolution-9bb3bdff6217

I think it would be helpful to add this information to the documentation. The documentation currently does not have any results for the queries "onion" or "tor".

**Comment by makoto** [comment]
Added onion example at https://github.com/ensdomains/docs/pull/53/files#diff-32636c5d9b1a806f351c48d5480968bce89da243033d790e02c0c0e5ef0e6cc3R190
