### ISSUE TITLE
Update list of traditional domains on the DNS registrar guide

### ISSUE THREAD

**Issue by TheodoreChu** [ensdomains/docs#48]
The landing page of ENS Domains (https://ens.domains) says that the following traditional domains are supported: `.xyz`, `.kred`, `.luxe`, `.club`, `.art`. I have two suggestions:

1. Add this list to the top / introduction of the [DNS Registrar guide](https://docs.ens.domains/dns-registrar-guide) so that searching for "xyz", "kred", "luxe", "club", and "art" will bring up the guide.
2. Update the list of these domains in the FAQ of the DNS Registrar guide because it is outdated. The first question of the FAQ says, "Why are only `.xyz`, `.luxe` and `kred` domains supported?"

**Comment by makoto** [comment]
Solved at https://github.com/ensdomains/docs/pull/50
