### ISSUE TITLE
Outdated example for DNSRegistrar

### ISSUE THREAD

**Issue by Gh05d** [ensdomains/docs#75]
In the [docs](https://docs.ens.domains/contract-api-reference/dns-registrar#submitting-the-proof-to-the-dnsregistrar) in  the example for _Submitting the proof to the DNSRegistrar_, the import for the `abi` seems to be outdated. In the docs it is:

`import { abi } from '@ensdomains/contracts/abis/dnsregistrar/DNSRegistrar.json'`

but checking the _node_modules_ it should be this:

`import abi from "@ensdomains/ens-contracts/build/contracts/DNSRegistrar.json";`

Maybe also add a comment that for this to work, the [experimental flag](https://nodejs.org/api/esm.html#json-modules) has to be set.

**Comment by lucemans** [comment]
Will be updated in v2
