### ISSUE TITLE
Missing import / declaration for variable claim.encodedName in example

### ISSUE THREAD

**Issue by Gh05d** [ensdomains/docs#77]
On line 14 of the [Submitting the proof to the DNSRegistrar](https://docs.ens.domains/contract-api-reference/dns-registrar#submitting-the-proof-to-the-dnsregistrar) example, there is the variable `claim.encodedName` used, which is neither imported nor declared beforehand.

Would be beneficial to show where it comes from with maybe a comment to explain what it does.

**Comment by lucemans** [comment]
Will be updated in v2
