### ISSUE TITLE
Incorrect variable destructering in example for DNSRegistrar

### ISSUE THREAD

**Issue by Gh05d** [ensdomains/docs#78]
On line 10 of the [Submitting the proof to the DNSRegistrar](https://docs.ens.domains/contract-api-reference/dns-registrar#submitting-the-proof-to-the-dnsregistrar) example, `data` and `proof` get destructured:

`const { data, proof } = oracle.getProofData(result)`

But `data` does not exist in the object. It should be `rrsets` instead:

`const { rrsets, proof } = oracle.getProofData(result)`

**Comment by lucemans** [comment]
Will be updated in v2
