### ISSUE TITLE
Main ENS project board is a bit stale

### ISSUE THREAD

**Issue by philipmather** [ensdomains/docs#86]
Appologies for recording this in the wrong place but this seemed the next best place.
Your main project board https://github.com/orgs/ensdomains/projects/1 seems a bit stale, the only two issues marked as "Good First Issue" and sat in "todo" are both completed...

https://github.com/ensdomains/ens-app/issues/943
https://github.com/ensdomains/ens-app/issues/1140

I assume more are perhaps but these were the only two I checked.

**Comment by Arachnid** [comment]
Thanks for pointing this out! We mostly use the board for tracking internal team project work, but we could definitely do a better job of tagging stuff for external contributions.

@jefflau @LeonmanRolls Could you take a look?

**Comment by jefflau** [comment]
@LeonmanRolls Does it make sense for people to keep contributing to the ens-app repo with the redesign? I know you tagged some stuff with post redesign and pre-design.
