### ISSUE TITLE
ESIP-11 mentions both 0x80000000 and 0x800000000 (latter has 1 more `0`)

### ISSUE THREAD

**Issue by hboon** [ensdomains/docs#89]
The larger value has 1 too many `0`.

Not sure if I should create a PR to edit.

https://github.com/ensdomains/docs/blob/master/ens-improvement-proposals/ensip-11-evmchain-address-resolution.md

**Comment by makoto** [comment]
Thank you for the report. Fixed at https://github.com/ensdomains/docs/pull/90
